import type { Metadata } from "next";
import { Pixelify_Sans, Press_Start_2P } from "next/font/google";
import "./globals.css";
import { MantineProvider, ColorSchemeScript, AppShell, AppShellHeader, AppShellMain, AppShellFooter } from "@mantine/core";
import "@mantine/core/styles.css";
import { Header } from "@/components/Header/Header";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { Footer } from "@/components/Footer/Footer";
const pixelify_sans = Pixelify_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = {
  fontFamily: pixelify_sans.style.fontFamily,
  headings: {
    fontFamily: pixelify_sans.style.fontFamily,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <ColorSchemeScript />
        </head>
        <body>
          <MantineProvider defaultColorScheme="light" theme={theme} withGlobalClasses>
            <AppShell header={{ height: 60 }}>
              <AppShellHeader>
                <Header></Header>
              </AppShellHeader>
              <AppShellMain>{children}</AppShellMain>
              <Footer></Footer>
            </AppShell>
          </MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
